version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - /home/eway/docker_test/:/home/crush
    sysctls:
      net.ipv4.ip_local_port_range: 49152 65535
networks:
  default:
